install.packages("mongolite")
library(mongolite)
setwd("D:\\ACS\\BEDU\\Modulo 2\\Postwork_7")
data <- read.csv("data.csv")
query <- mongo(collection = "match_games", db= "match", url = "mongodb+srv://AdrianCS14:1234@clusterbedu.ntmgn.mongodb.net/admin")
db=read.csv("data.csv")
query$insert(db)
query$count()
query$find('{"date" : "2015-12-20"}')
query$disconnect()
